baseurl = "http://rbh007.github.io/bit-xpert/"
languageCode = "ro"
title = "Bit-Xpert"
theme = "hugo-creative-theme"
canonifyurls = true

[params]

	# You can use Markdown syntax for urls [text](//url.to/source) for
	# most longer texts.

	# All icons using Fontawesome's icon font. Look at fortawesome.github.io/Font-Awesome/icons/
	# for more icons. The icons are represented by their corresponding
	# CSS class.

	# All projects of the portfolio are defined in their own files.
	# You can find example projects at 'exampleSite/data/projects'. Copy the 'projects'
	# folder into the 'data' directory at the root of this Hugo site.
	# For more informtion take a look at the README.

	# To provide some metadata for search engines feel free to add a few
        # information about you and your website.  name = "Bit-Xpert"
	description = "Bit-Xpert va ofera la preturi negociabile
	servicii de instalare / inlocuire / diagnosticare / testare
	componente hardware, recuperari date, devirusari, instalari / configurari
	software si echipamente periferice, configurari retele,
	consultanta IT"

	# The path must be relative to the static folder
	favicon = "favicon.ico"


	# Navigation
	[params.navigation]
		brand = "Bit-Xpert"

		[params.navigation.links]
			about     = "Despre noi"
			services  = "De ce noi"
			portfolio = "Servicii"
			contact   = "Contact"


	# Hero section
	[params.hero]
		# To change the background of the hero section,
		# replace the 'header.jpg' at './static/img' with your
		# own.
		slogan     = "Bit-Xpert Service"
		subtitle   = ""
		buttonText = "Afla Mai Multe"


	# About section
	[params.about]
		headline    = "Probleme cu calculatorul?"
		description = "Bit-Xpert Va ofera la preturi
		negociabile servicii de Instalare / Inlocuire /
		Diagnosticare / Testare componente Hardware ,
		Instalari / Reinstalari / Configurari SO, Recuperari
		Date, Devirusari, Instalari / Configurari Software si
		Echipamente Periferice, Configurari Retele,
		Consultanta IT."
		buttonText  = "Avantaje"


	# Service section
	[params.services]
		headline = "De ce noi?"

        [[params.services.list]]
            icon = "fa-eur"
            title = "Preturi negociabile"
            description = "Indiferent de proiect, beneficiati de preturi competitive"

        [[params.services.list]]
			icon = "fa-cogs"
			title = "Consultanta"
			description = "Solutionarea rapida a neclaritatilor dvs."

		[[params.services.list]]
            icon = "fa-bullhorn"
            title = "Reduceri"
            description = "Discount substantial la prima interventie"

        [[params.services.list]]
            icon = "fa-rocket"
            title = "Raspuns rapid"
            description = "Preluare / predare rapida a echipamentelor"


    # Portfolio modals
	[params.portfolio.modal]
        client = ""
        date = ""
        category = ""
        buttonText = "Inchide"

    # Aside section
	[params.aside]
		headline = "Pentru lista completa a serviciilor va rugam folositi informatiile de contact"

		[params.aside.button]
			text = "Contact"
			link = "#contact"

	# Contact section
	[params.contact]
		headline = "Contactati Xpertul"
		description = "Pentru orice fel de nelamuriri nu ezitati sa ne contactati."
		phone = "0765 666 676"
		email = "bit.xpert.it@gmail.com"
